sudo: false

os:
  - osx
  - linux

env:
  - TEST_DIR=extension

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - cd $TEST_DIR
  - npm install
  - npm run vscode:prepublish

script:
  - cd $TEST_DIR
  - npm test --silent
